# Generated by Django 4.0.1 on 2022-01-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateapi', '0002_alter_myuuidmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuuidmodel',
            name='updated_at',
        ),
    ]
