# Generated by Django 4.0.1 on 2022-01-16 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateapi', '0008_alter_myuuidmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuidmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 16, 21, 36, 42, 397071), null=True),
        ),
    ]
