# Generated by Django 4.0.1 on 2022-01-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateapi', '0009_alter_myuuidmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuidmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
